# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0558df1cea3a7fa319c8e4bf0222d7b4061628f7a13b54656266fe3f663c86a3a01b039ff63fff53db12dd056b724c1c6bf08f724d1052c2a22676f1a2281b4

test:
  secret_key_base: d9bd5c377dbb6e550acbf4d385266ed20af28822839b2d3c13eebaf5db99a0a2b034e3cee99b95c385927a37bfaf15426b0d2462d7dc518d3548945170349ee4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
